### ISSUE TITLE
Update devDependancies

### ISSUE THREAD

**Issue by NateBaldwinDesign** [NateBaldwinDesign/aggregator#26]
Gemnasium indicates gulp-json-transform is not up to date. Need to update all deps to make sure it's good to go.

**Comment by GustavoKatel** [comment]
It seems that is already on the latest version `"gulp-json-transform": "^0.4.2"`. It maybe just requires to refresh the repo in your Gemnasium account

**Comment by NateBaldwinDesign** [comment]
Thank you Gustavo I will take a look on the account and close this issue
