### ISSUE TITLE
Gemnasium badge is pointing to the wrong repo

### ISSUE THREAD

**Issue by GustavoKatel** [NateBaldwinDesign/aggregator#29]
I think this is related to #26 . You are pointing the badge to https://github.com/NateBaldwinDesign/aggregator

Ps.: Which redirects to Dragoman (Did you change the name of the repo?), but apparently Gemnasium see as two different things

**Comment by NateBaldwinDesign** [comment]
Updated account & url for gemnasium (https://github.com/NateBaldwinDesign/Dragoman/commit/8058de276a0f0b672e5a31540c6de9022cb4d519)
