### ISSUE TITLE
svg2png gulp task debugging

### ISSUE THREAD

**Issue by NateBaldwinDesign** [NateBaldwinDesign/aggregator#31]
Gulp file "gulp/icons-ios" is breaking. The module "gulp-svg2png" is breaking. Currently the require variable is commented out to prevent it from breaking build process.
1) un-comment // svg2png = ('gulp-svg2png'),
2) debug and identify what is breaking this module from converting svg icons to png images
3) test using gulp task "icons-ios"

**Comment by m5r** [comment]
Using the gulp task icons-ios does not break. I actually have the correct .png output. What is wrong with it ?

![](https://i.gyazo.com/286877ae0c805232d40efeed563d9d9b.png)

**Comment by NateBaldwinDesign** [comment]
@MomoGunz, thank you for looking at this. It appears that the issue may be local issue with the plugin.  I will close this issue, thank you for checking it out!
