### ISSUE TITLE
jekyll page not working

### ISSUE THREAD

**Issue by NateBaldwinDesign** [NateBaldwinDesign/aggregator#38]
gh-pages branch generating jekyll page not working -- generated jekyll site (on repo url) is throwing 404 error.

**Comment by chrislambcodes** [comment]
Page is accessible at: https://natebaldwindesign.github.io/dragoman/. Repo url is https://natebaldwindesign.github.io/Dragoman/. Simply change the 'd' to lowercase in repo options.
