### ISSUE TITLE
Optimize jekyll page build

### ISSUE THREAD

**Issue by NateBaldwinDesign** [NateBaldwinDesign/aggregator#41]
add to _config.yml along with fixing this problem is that there are certain unnecessary files and folders (eg; config.rb, Gemfile, Gemfile.lock and node_modules ) copied over to generated _site folder while running jekyll build. This copying of extra files may further slowdown development process when you run jekyll serve without --no-watch.

**Comment by kushalpandya** [comment]
I'll push in another PR for the same. :smiley:
